sudo: false

git:
    depth: 10

language: php

php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
    - '8.0snapshot'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/psalm
    - vendor/bin/phpunit
